# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.6/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.6/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Cedric/Documents/CloudStation/School/GP/Gradius

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Cedric/Documents/CloudStation/School/GP/Gradius

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.6/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/Cellar/cmake/3.9.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Cedric/Documents/CloudStation/School/GP/Gradius/CMakeFiles /Users/Cedric/Documents/CloudStation/School/GP/Gradius/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Cedric/Documents/CloudStation/School/GP/Gradius/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Gradius

# Build rule for target.
Gradius: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gradius
.PHONY : Gradius

# fast build rule for target.
Gradius/fast:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/build
.PHONY : Gradius/fast

Controller.o: Controller.cpp.o

.PHONY : Controller.o

# target to build an object file
Controller.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Controller.cpp.o
.PHONY : Controller.cpp.o

Controller.i: Controller.cpp.i

.PHONY : Controller.i

# target to preprocess a source file
Controller.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Controller.cpp.i
.PHONY : Controller.cpp.i

Controller.s: Controller.cpp.s

.PHONY : Controller.s

# target to generate assembly for a file
Controller.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Controller.cpp.s
.PHONY : Controller.cpp.s

Entity.o: Entity.cpp.o

.PHONY : Entity.o

# target to build an object file
Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Entity.cpp.o
.PHONY : Entity.cpp.o

Entity.i: Entity.cpp.i

.PHONY : Entity.i

# target to preprocess a source file
Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Entity.cpp.i
.PHONY : Entity.cpp.i

Entity.s: Entity.cpp.s

.PHONY : Entity.s

# target to generate assembly for a file
Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Entity.cpp.s
.PHONY : Entity.cpp.s

EntityRepresentation.o: EntityRepresentation.cpp.o

.PHONY : EntityRepresentation.o

# target to build an object file
EntityRepresentation.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/EntityRepresentation.cpp.o
.PHONY : EntityRepresentation.cpp.o

EntityRepresentation.i: EntityRepresentation.cpp.i

.PHONY : EntityRepresentation.i

# target to preprocess a source file
EntityRepresentation.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/EntityRepresentation.cpp.i
.PHONY : EntityRepresentation.cpp.i

EntityRepresentation.s: EntityRepresentation.cpp.s

.PHONY : EntityRepresentation.s

# target to generate assembly for a file
EntityRepresentation.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/EntityRepresentation.cpp.s
.PHONY : EntityRepresentation.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Game.cpp.s
.PHONY : Game.cpp.s

Model.o: Model.cpp.o

.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i

.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s

.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Model.cpp.s
.PHONY : Model.cpp.s

MovingEntity.o: MovingEntity.cpp.o

.PHONY : MovingEntity.o

# target to build an object file
MovingEntity.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/MovingEntity.cpp.o
.PHONY : MovingEntity.cpp.o

MovingEntity.i: MovingEntity.cpp.i

.PHONY : MovingEntity.i

# target to preprocess a source file
MovingEntity.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/MovingEntity.cpp.i
.PHONY : MovingEntity.cpp.i

MovingEntity.s: MovingEntity.cpp.s

.PHONY : MovingEntity.s

# target to generate assembly for a file
MovingEntity.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/MovingEntity.cpp.s
.PHONY : MovingEntity.cpp.s

PlayerShip.o: PlayerShip.cpp.o

.PHONY : PlayerShip.o

# target to build an object file
PlayerShip.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/PlayerShip.cpp.o
.PHONY : PlayerShip.cpp.o

PlayerShip.i: PlayerShip.cpp.i

.PHONY : PlayerShip.i

# target to preprocess a source file
PlayerShip.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/PlayerShip.cpp.i
.PHONY : PlayerShip.cpp.i

PlayerShip.s: PlayerShip.cpp.s

.PHONY : PlayerShip.s

# target to generate assembly for a file
PlayerShip.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/PlayerShip.cpp.s
.PHONY : PlayerShip.cpp.s

StationaryEntity.o: StationaryEntity.cpp.o

.PHONY : StationaryEntity.o

# target to build an object file
StationaryEntity.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/StationaryEntity.cpp.o
.PHONY : StationaryEntity.cpp.o

StationaryEntity.i: StationaryEntity.cpp.i

.PHONY : StationaryEntity.i

# target to preprocess a source file
StationaryEntity.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/StationaryEntity.cpp.i
.PHONY : StationaryEntity.cpp.i

StationaryEntity.s: StationaryEntity.cpp.s

.PHONY : StationaryEntity.s

# target to generate assembly for a file
StationaryEntity.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/StationaryEntity.cpp.s
.PHONY : StationaryEntity.cpp.s

Stopwatch.o: Stopwatch.cpp.o

.PHONY : Stopwatch.o

# target to build an object file
Stopwatch.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Stopwatch.cpp.o
.PHONY : Stopwatch.cpp.o

Stopwatch.i: Stopwatch.cpp.i

.PHONY : Stopwatch.i

# target to preprocess a source file
Stopwatch.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Stopwatch.cpp.i
.PHONY : Stopwatch.cpp.i

Stopwatch.s: Stopwatch.cpp.s

.PHONY : Stopwatch.s

# target to generate assembly for a file
Stopwatch.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Stopwatch.cpp.s
.PHONY : Stopwatch.cpp.s

Transformation.o: Transformation.cpp.o

.PHONY : Transformation.o

# target to build an object file
Transformation.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Transformation.cpp.o
.PHONY : Transformation.cpp.o

Transformation.i: Transformation.cpp.i

.PHONY : Transformation.i

# target to preprocess a source file
Transformation.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Transformation.cpp.i
.PHONY : Transformation.cpp.i

Transformation.s: Transformation.cpp.s

.PHONY : Transformation.s

# target to generate assembly for a file
Transformation.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/Transformation.cpp.s
.PHONY : Transformation.cpp.s

View.o: View.cpp.o

.PHONY : View.o

# target to build an object file
View.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/View.cpp.o
.PHONY : View.cpp.o

View.i: View.cpp.i

.PHONY : View.i

# target to preprocess a source file
View.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/View.cpp.i
.PHONY : View.cpp.i

View.s: View.cpp.s

.PHONY : View.s

# target to generate assembly for a file
View.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/View.cpp.s
.PHONY : View.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Gradius.dir/build.make CMakeFiles/Gradius.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Gradius"
	@echo "... Controller.o"
	@echo "... Controller.i"
	@echo "... Controller.s"
	@echo "... Entity.o"
	@echo "... Entity.i"
	@echo "... Entity.s"
	@echo "... EntityRepresentation.o"
	@echo "... EntityRepresentation.i"
	@echo "... EntityRepresentation.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... MovingEntity.o"
	@echo "... MovingEntity.i"
	@echo "... MovingEntity.s"
	@echo "... PlayerShip.o"
	@echo "... PlayerShip.i"
	@echo "... PlayerShip.s"
	@echo "... StationaryEntity.o"
	@echo "... StationaryEntity.i"
	@echo "... StationaryEntity.s"
	@echo "... Stopwatch.o"
	@echo "... Stopwatch.i"
	@echo "... Stopwatch.s"
	@echo "... Transformation.o"
	@echo "... Transformation.i"
	@echo "... Transformation.s"
	@echo "... View.o"
	@echo "... View.i"
	@echo "... View.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

